[package]
name = "extract-zip-from-http"
version = "0.1.0"
edition = "2024"

license = "MIT"
repository = "https://github.com/OgGhostJelly/extract-zip-from-http"

[dependencies]
inflate = "0.4.5"
thiserror = "2.0.17"
ureq = "3.1.2"
